// UI fonts generated by scripts/gen_fonts.sh (see README.md in this folder).
//
// Unlike LVGL's built-in Montserrat (ASCII + "°" + "•" only) these cover
// Latin-1 (é è à ç ô ü ß …), French/English typography (’ “ ” – — … • ·),
// "λ", "€", arrows and every LV_SYMBOL_* glyph — the daemon sends agent
// names, summaries and questions in the user's own language.
#pragma once

#include "lvgl.h"

LV_FONT_DECLARE(font_ui_14);    // body text
LV_FONT_DECLARE(font_ui_20);    // agent name, titles
LV_FONT_DECLARE(font_ui_28);    // big numbers / icons (ASCII + symbols + λ)
LV_FONT_DECLARE(font_logo_72);  // boot logo: "λ" only
